Spawning one ops pod for each node in the cluster. (#248)
* Spawning one ops pod for each node in the cluster.

That way operators can easily debug more than one nodes in the cluster

* Apply suggestions from code review

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

* Correcting podname

* Changing metadata according to Plamen's ideas

Co-authored-by: Plamen Kokanov <35485709+plkokanov@users.noreply.github.com>

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>
Co-authored-by: Plamen Kokanov <35485709+plkokanov@users.noreply.github.com>

diff --git a/hacks/ops-pod b/hacks/ops-pod
--- a/hacks/ops-pod
+++ b/hacks/ops-pod
@@ -9,10 +9,9 @@
 function print_usage() {
   cat <<EOF
 ops-pod: Deploy privileged pod in a kubernetes cluster and open terminal into cluster node using the current kubectl context.
-         When specifying <pod-name> the node of the specified pod will be used.
 
 Usage:
-  ops-pod [OPTIONS] <node|pod-name>
+  ops-pod [OPTIONS] <node>
 
 Options:
   -n|--namespace    The namespace into which the pod will be deployed. The namespace of the current kubectl context is used by default.
@@ -45,11 +44,22 @@ hostnetwork="false"
 copy_tolerations=${FALSE}
 node_chroot=${FALSE}
 sanitize_hostname() {
+  prefix="${1}"
+  suffix="${2}"
+  join_symbol="-"
+  # max len we want is 31 symbols.
+  # we get `-` between username and the prefix, hence we calculate from 30
+  if [ "${#suffix}" -gt $((30 - ${#prefix})) ]; then
+    join_symbol=""
+    prefix=""
+  fi
   # K8s rejects pod names that violate this RE '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
   # due to RFC1123 (Only allow lower-case and alphanumerical values for hostnames)
-  echo "$@" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g'
+  rfc1123_name="$(echo "${prefix}${join_symbol}${suffix}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')"
+  rfc1123_name="${rfc1123_name:0:30}"
+  echo "${rfc1123_name}"
 }
-name="$(sanitize_hostname "ops-pod-$(whoami)")"
+
 
 default_image="europe-docker.pkg.dev/gardener-project/releases/gardener/ops-toolbelt:latest"
 function get_default_namespace() {
@@ -95,7 +105,7 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ ${#positional[@]} -ne 1 ]]; then
-  echo -e "Error: Required one positional argument: <node|pod-name> found ${#positional[@]}\n"
+  echo -e "Error: Required one positional argument: <node> found ${#positional[@]}\n"
   print_usage
   exit 1
 fi
@@ -104,25 +114,19 @@ node=${positional[0]}
 image=${image:-$default_image}
 namespace=${namespace:-$(get_default_namespace)}
 
-node_of_pod=$(kubectl -n "${namespace}" get pod "${node}" -o 'jsonpath={.spec.nodeName}' 2>/dev/null || true)
-if [[ -n ${node_of_pod} ]]; then
-  echo -e "Pod name provided. Deploying ops pod on the node where ${node} is running: ${node_of_pod}\n"
-  node=$node_of_pod
+if kubectl get nodes -o jsonpath='{.items[*].metadata.name}' | grep -q "\b${node}\b"; then
+  echo -e "Deploying ops pod on ${node}\n"
 else
-  echo "Node name provided ..."
-  if kubectl get nodes -o jsonpath='{.items[*].metadata.name}' | grep -q "\b${node}\b"; then
-    echo -e "Deploying ops pod on ${node}\n"
-  else
-    echo -e "Error: node ${node} does not exist in the cluster.\n"
-    print_usage
-    exit 2
-  fi
+  echo -e "Error: node ${node} does not exist in the cluster.\n"
+  print_usage
+  exit 2
 fi
-
-# check if the node name was a pod name and we should actually identify the node from the pod (node that runs the pod)
 
 # Kubify nodes have labels that differ from the names (need an additional suffix)
 node=$(echo "$node" | sed -r "s/^(garden-.*)/\1.openstack.local/")
+
+# Set pod name to be unique and deterministic for the given node
+name="$(printf '%s-%s' "$(sanitize_hostname "ops-pod" "$(whoami)")" "$(printf '%s' "${node}" | md5sum | awk '{print $1}')" )"
 
 if [[ $copy_tolerations -eq $TRUE ]]; then
   tolerations_array=$(kubectl get nodes "${node}" -o jsonpath='{range .spec.taints[*]}  - effect: "{@.effect}"{"\n"}    key: "{@.key}"{"\n"}    value: "{@.value}"{"\n"}    operator: "{@.operator}"{"\n"}{end}')
@@ -140,12 +144,18 @@ done
 trap "EC=\$?; kubectl -n ${namespace} delete pod ${name} --wait=false  >&2 || true; exit \$EC" EXIT INT TERM
 
 # launch pod
-kubectl -n "${namespace}" create -f <(
+kubectl create -f <(
   cat <<EOF
 apiVersion: v1
 kind: Pod
 metadata:
   name: $name
+  namespace: $namespace
+  labels:
+    ops-toolbelt.gardener.cloud/managed-by: "https://github.com/gardener/ops-toolbelt/blob/master/hacks/ops-pod"
+    ops-toolbelt.gardener.cloud/user: $(whoami)
+    ops-toolbelt.gardener.cloud/user-machine-hostname: $(hostname)
+    ops-toolbelt.gardener.cloud/version: $(cat "$(dirname "$(readlink -f "$0")")/../VERSION")
 spec:
   $([[ -n $node ]] && echo -e "nodeSelector:\n    kubernetes.io/hostname: $node")
   tolerations:
